version: 2
jobs:
  build:
    docker:
      - image: node:8.11.1-alpine
    steps:
      - checkout
      - run:
          name: Install packages
          command: yarn install
      - run:
          name: Check the code format
          command: yarn prettier --single-quote --no-bracket-spacing --list-different **/*.js
      - run:
          name: Lint the code
          command: yarn eslint **/*.js
      - run:
          name: Run tests
          command: yarn jest
